<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sed_nivele extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sed_nivele_model');
    } 

    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('sed_nivele/index?');
        $config['total_rows'] = $this->Sed_nivele_model->get_all_sed_niveles_count();
        $this->pagination->initialize($config);

        $data['sed_niveles'] = $this->Sed_nivele_model->get_all_sed_niveles($params);
        
        $data['_view'] = 'sed_nivele/index';
        $this->load->view('layouts/main',$data);
    }

    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nombre','Nombre','max_length[50]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nombre' => $this->input->post('nombre'),
				'estado' => $this->input->post('estado'),
            );
            
            $sed_nivele_id = $this->Sed_nivele_model->add_sed_nivele($params);
            redirect('sed_nivele/index');
        }
        else
        {            
            $data['_view'] = 'sed_nivele/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    function edit($id_nivel)
    {   
        $data['sed_nivele'] = $this->Sed_nivele_model->get_sed_nivele($id_nivel);
        
        if(isset($data['sed_nivele']['id_nivel']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nombre','Nombre','max_length[50]');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nombre' => $this->input->post('nombre'),
					'estado' => $this->input->post('estado'),
                );

                $this->Sed_nivele_model->update_sed_nivele($id_nivel,$params);            
                redirect('sed_nivele/index');
            }
            else
            {
                $data['_view'] = 'sed_nivele/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The sed_nivele you are trying to edit does not exist.');
    } 

    function remove($id_nivel)
    {
        $sed_nivele = $this->Sed_nivele_model->get_sed_nivele($id_nivel);

        if(isset($sed_nivele['id_nivel']))
        {
            $this->Sed_nivele_model->delete_sed_nivele($id_nivel);
            redirect('sed_nivele/index');
        }
        else
            show_error('The sed_nivele you are trying to delete does not exist.');
    }
    
}
