<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sed_periodos_detalle_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    

    function get_sed_periodos_detalle($secuencia)
    {
        return $this->db->get_where('sed_periodos_detalle',array('secuencia'=>$secuencia))->row_array();
    }
    

    function get_all_sed_periodos_detalle_count()
    {
        $this->db->from('sed_periodos_detalle');
        return $this->db->count_all_results();
    }
        

    function get_all_sed_periodos_detalle($params = array())
    {
        $this->db->order_by('secuencia', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('sed_periodos_detalle')->result_array();
    }
        

    function add_sed_periodos_detalle($params)
    {
        $this->db->insert('sed_periodos_detalle',$params);
        return $this->db->insert_id();
    }
    

    function update_sed_periodos_detalle($secuencia,$params)
    {
        $this->db->where('secuencia',$secuencia);
        return $this->db->update('sed_periodos_detalle',$params);
    }
    

    function delete_sed_periodos_detalle($secuencia)
    {
        return $this->db->delete('sed_periodos_detalle',array('secuencia'=>$secuencia));
    }
}
